<a href="https://colab.research.google.com/github/Akash-mf/-Data-Analysis-with-Python-and-Pandas/blob/main/Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [143]:
import numpy as np

In [144]:
print(np)

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>


In [145]:
print(np. __version__)

2.0.2


In [146]:
my_list = [1,2,3,4,5]


In [147]:
print(my_list)

[1, 2, 3, 4, 5]


In [148]:
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [149]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [150]:
print(type(array))

<class 'numpy.ndarray'>


In [151]:
array = array * 2
print(array)

[2 4 6 8]


In [152]:
print(type(array))

<class 'numpy.ndarray'>


In [153]:
#ndim = No.of dimension of an array
array = np.array('A')
print(array.ndim)

0


In [154]:
array = np.array([['A','B','C']])
print(array.ndim)

2


In [179]:
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y','Z', '']]])

print(array.ndim)  # Output: 2


3


In [180]:
print(array.shape)

(3, 3, 3)


In [181]:
print(array[0][0][0])

A


In [182]:
print(array[0,0,0])

A


In [183]:
print(array[0,0,1])

B


In [184]:
print(array[0,0,3])

IndexError: index 3 is out of bounds for axis 2 with size 3

In [185]:
print(array[0,1,0])

D


In [186]:
print(array[0,1,1])

E


In [187]:
print(array[1,1,1])

N


In [188]:
word = array[0,0,0] + array[2,0,0]
print(word)

AS


In [189]:
word = array[0,0,0] + array[2,0,0] + array[2,0,0]
print(word)

ASS


In [191]:
# 2D  array
import numpy as ak
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [192]:
#array[start:endL:Step]
print(array[0])

[1 2 3 4]


In [193]:
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [194]:
print(array[1])

[5 6 7 8]


In [195]:
print(array[2])

[ 9 10 11 12]


In [196]:
print(array[3])

[13 14 15 16]


In [197]:
print(array[4])

IndexError: index 4 is out of bounds for axis 0 with size 4

In [198]:
print(array[-1])

[13 14 15 16]


In [199]:
print(array[-2])

[ 9 10 11 12]


In [200]:
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [201]:
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [202]:
print(array[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [203]:
print(array[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [204]:
print(array[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [205]:
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [206]:
print(array[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [207]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [208]:
print(array[0,0])

1


In [209]:
print(array[:,0])

[ 1  5  9 13]


In [211]:
print(array[:,1])

[ 2  6 10 14]


In [212]:
print(array[:,2])

[ 3  7 11 15]


In [213]:
print(array[:,3])

[ 4  8 12 16]


In [214]:
print(array[:,-1])

[ 4  8 12 16]


In [215]:
print(array[:,-2])

[ 3  7 11 15]


In [216]:
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [217]:
print(array[:,1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [218]:
print(array[:,1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [219]:
print(array[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [220]:
print(array[:,1:2])

[[ 2]
 [ 6]
 [10]
 [14]]


In [221]:
print(array[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [222]:
print(array[:,::-2])

[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [223]:
print(array[0,0])

1


In [224]:
print(array[0:2,0])

[1 5]


In [225]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [226]:
print(array[0:2,2:4])

[[3 4]
 [7 8]]


In [227]:
print(array[0:2,0:])

[[1 2 3 4]
 [5 6 7 8]]


In [228]:
print(array[2:,0:2])

[[ 9 10]
 [13 14]]


In [230]:
print(array[2:,2:5])

[[11 12]
 [15 16]]


In [232]:
print(array[2:, 2:])

[[11 12]
 [15 16]]


In [233]:
#Arithmetic
import numpy as kp

#Scalar arithmetic

array = kp.array([1,2,3])


In [234]:
print(array + 1)

[2 3 4]


In [235]:
print(array - 2)

[-1  0  1]


In [236]:
print(array * 3)

[3 6 9]


In [237]:
print(array / 4)

[0.25 0.5  0.75]


In [238]:
print(array ** 5)

[  1  32 243]


In [239]:
#Vectorized math functions
import numpy as np
array = np.array([1,2,3])

print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [240]:
array = np.array([1.01, 2.5, 3.99])
print(np.round(array))

[1. 2. 4.]


In [241]:
print(np.floor(array))

[1. 2. 3.]


In [242]:
print(np.ceil(array))

[2. 3. 4.]


In [243]:
print(np.round(array))

[1. 2. 4.]


In [244]:
print(np.pi)

3.141592653589793


In [246]:
#Exercise
radii = np.array([1,2,3])

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [247]:
print(array1 + array2)

[5 7 9]


In [248]:
print(array1 - array2)

[-3 -3 -3]


In [249]:
print(array1 * array2)

[ 4 10 18]


In [250]:
print(array1 / array2)

[0.25 0.4  0.5 ]


In [251]:
print(array1 ** array2)

[  1  32 729]


In [252]:
import numpy as jk
scores = np.array([91, 55, 100, 73, 82, 64])

In [253]:
print(scores == 100)

[False False  True False False False]


In [254]:
print(scores >= 60)

[ True False  True  True  True  True]


In [255]:
print(scores < 60)

[False  True False False False False]


In [257]:
scores [scores < 60] = 0

In [259]:
print(scores)

[ 91   0 100  73  82  64]


In [260]:
import numpy as all

array1 = all.array([[1,2,3,4]])
array2 = all.array([[1],[2],[3],[4]])

print(array1.shape)

(1, 4)


In [261]:

print(array2.shape)

(4, 1)


In [262]:

print(array1 * array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [265]:
import numpy as al  # Correct alias

# Properly define array1 as a 4x4 matrix
array1 = al.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Properly define array2 as a 4x1 matrix
array2 = al.array([
    [1],
    [2],
    [3],
    [4]
])

# Print shape of array1
print("array1 shape:", array1.shape)

# Print shape of array2
print("array2 shape:", array2.shape)


array1 shape: (4, 4)
array2 shape: (4, 1)


In [267]:
import numpy as jp  # Correct alias

# Properly define array1 as a 4x4 matrix
array1 = jp.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Properly define array2 as a 4x2 matrix (each row has exactly 2 elements)
array2 = jp.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5]
])

# Print shape of array1
print("array1 shape:", array1.shape)

# Print shape of array2
print("array2 shape:", array2.shape)



array1 shape: (4, 4)
array2 shape: (4, 2)


In [269]:
import numpy as num

array1 = num.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = num.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [272]:
#aggregate fuctions
import numpy as agg

array = agg.array([[1,2,3,4,5],
                   [6,7,8,9,10]])

In [273]:
print(agg.sum(array))

55


In [274]:
print(agg.mean(array))

5.5


In [277]:
print(agg.std(array))

2.8722813232690143


In [278]:
print(agg.var(array))

8.25


In [279]:
print(agg.min(array))

1


In [280]:
print(agg.max(array))

10


In [281]:
print(agg.argmin(array))

0


In [282]:
print(agg.argmax(array))

9


In [285]:
import numpy as pk
array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(pk.sum(array, axis = 0))


SyntaxError: incomplete input (ipython-input-844719284.py, line 5)

In [286]:
print(pk.sum(array, axis=1))


[15 40]


In [287]:
#Filtering - refers to the process of selecting elements from an array that matching a given coonditions.
import numpy as np

ages = np.array([[21, 17, 19, 20, 16, 30,18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

In [289]:
teenagers = ages[ages < 18]
print(ages)

[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]


In [290]:
adults = ages[ages >= 18]
adults = ages[(ages>=18) & (ages < 65)]
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [291]:
adults = ages[(ages<18)]
adults = ages[(ages < 18)| (ages >= 65)]
print(adults)

[17 16 65 15 99]


In [294]:
import numpy as kjj

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]

adults = ages[(ages >= 18) & (ages < 65)]

seniors = ages[ages >= 65]

evens = ages[ages%2 == 0]

odds = ages[ages%2 != 0]

print(seniors)

print(evens)

[65 99]
[20 16 30 18 22 18 20]


In [298]:
#WHERE
import numpy as kk

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

adults = kk.where(ages >= 18, ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [299]:
import numpy as pn

rng = pn.random.default_rng()

print(rng.integers(low = 1, high = 7))

2


In [300]:
print(rng.integers(low = 1, high = 101))

78


In [304]:
print(rng.integers(low = 1, high = 101, size = 3))

[65 25 75]


In [305]:
print(rng.integers(low = 1, high = 7, size = (3,3)))

[[4 2 5]
 [2 1 1]
 [6 2 5]]


In [306]:
import numpy as np

rng = np.random.default_rng(seed = 1)


print(rng.integers(low = 1, high = 101, size= (3,2)))


[[48 52]
 [76 96]
 [ 4 15]]


In [307]:
import numpy as np

print(np.random.uniform())

0.6164440217503172


In [308]:
print(np.random.uniform(low = -1, high = 1, size = 3))

[ 0.2521352  -0.03319907 -0.09803941]


In [309]:
print(np.random.uniform(low = 1, high = 1, size =(3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [310]:
import numpy as np
np.random.seed(seed = 1)

print(np.random.uniform(low = -1, high = 1, size = (3,2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [312]:
import numpy as np
rng = np.random.default_rng()

array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[3 4 5 2 1]


In [313]:
import numpy as np
rng = np.random.default_rng()

fruits = np.array(["apple", "orange","banana", "Coconut","pineapple"])
fruit  = rng.choice(fruits)
print(fruits)

['apple' 'orange' 'banana' 'Coconut' 'pineapple']


In [314]:
import numpy as np
rng = np.random.default_rng()

fruits = np.array(["apple", "Orange", "banana", "cocount", "pineapple"])

fruit = rng.choice(fruits, size=3)
print(fruits)

['apple' 'Orange' 'banana' 'cocount' 'pineapple']


In [315]:
import numpy as np
rng = np.random.default_rng()

fruits = np.array(["apple", "Orange", "banana", "cocount", "pineapple"])

fruit = rng.choice(fruits, size=(3,3))
print(fruits)

['apple' 'Orange' 'banana' 'cocount' 'pineapple']
