<a href="https://colab.research.google.com/github/Akash-mf/-Data-Analysis-with-Python-and-Pandas/blob/main/Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [143]:
import numpy as np

In [144]:
print(np)

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>


In [145]:
print(np. __version__)

2.0.2


In [146]:
my_list = [1,2,3,4,5]


In [147]:
print(my_list)

[1, 2, 3, 4, 5]


In [148]:
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [149]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [150]:
print(type(array))

<class 'numpy.ndarray'>


In [151]:
array = array * 2
print(array)

[2 4 6 8]


In [152]:
print(type(array))

<class 'numpy.ndarray'>


In [153]:
#ndim = No.of dimension of an array
array = np.array('A')
print(array.ndim)

0


In [154]:
array = np.array([['A','B','C']])
print(array.ndim)

2


In [179]:
import numpy as np

array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y','Z', '']]])

print(array.ndim)  # Output: 2


3


In [180]:
print(array.shape)

(3, 3, 3)


In [181]:
print(array[0][0][0])

A


In [182]:
print(array[0,0,0])

A


In [183]:
print(array[0,0,1])

B


In [184]:
print(array[0,0,3])

IndexError: index 3 is out of bounds for axis 2 with size 3

In [185]:
print(array[0,1,0])

D


In [186]:
print(array[0,1,1])

E


In [187]:
print(array[1,1,1])

N


In [188]:
word = array[0,0,0] + array[2,0,0]
print(word)

AS


In [189]:
word = array[0,0,0] + array[2,0,0] + array[2,0,0]
print(word)

ASS


In [191]:
# 2D  array
import numpy as ak
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [192]:
#array[start:endL:Step]
print(array[0])

[1 2 3 4]


In [193]:
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [194]:
print(array[1])

[5 6 7 8]


In [195]:
print(array[2])

[ 9 10 11 12]


In [196]:
print(array[3])

[13 14 15 16]


In [197]:
print(array[4])

IndexError: index 4 is out of bounds for axis 0 with size 4

In [198]:
print(array[-1])

[13 14 15 16]


In [199]:
print(array[-2])

[ 9 10 11 12]


In [200]:
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [201]:
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [202]:
print(array[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [203]:
print(array[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [204]:
print(array[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [205]:
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [206]:
print(array[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [207]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [208]:
print(array[0,0])

1


In [209]:
print(array[:,0])

[ 1  5  9 13]


In [211]:
print(array[:,1])

[ 2  6 10 14]


In [212]:
print(array[:,2])

[ 3  7 11 15]


In [213]:
print(array[:,3])

[ 4  8 12 16]


In [214]:
print(array[:,-1])

[ 4  8 12 16]


In [215]:
print(array[:,-2])

[ 3  7 11 15]


In [216]:
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [217]:
print(array[:,1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [218]:
print(array[:,1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [219]:
print(array[:, ::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [220]:
print(array[:,1:2])

[[ 2]
 [ 6]
 [10]
 [14]]


In [221]:
print(array[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [222]:
print(array[:,::-2])

[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [223]:
print(array[0,0])

1


In [224]:
print(array[0:2,0])

[1 5]


In [225]:
print(array[0:2,0:2])

[[1 2]
 [5 6]]


In [226]:
print(array[0:2,2:4])

[[3 4]
 [7 8]]


In [227]:
print(array[0:2,0:])

[[1 2 3 4]
 [5 6 7 8]]


In [228]:
print(array[2:,0:2])

[[ 9 10]
 [13 14]]


In [230]:
print(array[2:,2:5])

[[11 12]
 [15 16]]


In [232]:
print(array[2:, 2:])

[[11 12]
 [15 16]]
